### ISSUE TITLE
i have error

### ISSUE THREAD

**Issue by Czekoladowy** [naschorr/auto-placer#4]
"TypeError when returning bool in checkCaptchaVisibility(), the element probably isn't in the DOM yet"

i write in console "let context = window.App;
$.getScript("https://rawgit.com/naschorr/color-converter/master/code/converter.js", function(){
	$.getScript("https://rawgit.com/naschorr/auto-placer/master/code/auto-placer.js", function(){
		new AutoPlacer(context, "https://i.imgur.com/AxKGmnJ.jpg", 50, 580);
	});
});"

**Comment by naschorr** [comment]
First things first, try running:
```
let context = window.App;
$.getScript("https://rawgit.com/naschorr/color-converter/master/code/converter.js", function(){
	$.getScript("https://rawgit.com/naschorr/auto-placer/master/code/auto-placer.js", function(){
		new AutoPlacer(context, "https://i.imgur.com/AxKGmnJ.jpg", 50, 580);
	});
});
```
again, I made a few changes that might fix things. If it still doesn't work, I'm going to need a bit more information.
- What browser are you using?
- Does the error happen every time you try to tun the script?
- Was that the only error in the console?
- Was anything else output to the console after the error?
- What happens when you type in `$("iframe[title$='recaptcha challenge']").parent().parent().get(0);`?
- What happens when you type in `grecaptcha;`?
- Are you running any extensions or scripts that would prevent the captcha from loading properly?

**Comment by Czekoladowy** [comment]
-im using opera
-everytime
- http://i.imgur.com/TzvpKOk.png
-"undefined"
-"Object {}"
i dont have any scripts

**Comment by Czekoladowy** [comment]
This is in chrome

http://i.imgur.com/MY5YIb3.png

**Comment by naschorr** [comment]
Since, `grecaptcha;` displays an object, but the `$("iframe...` query doesn't, something would seem to be wrong with the selector (or the hierarchy is different). Could you give me the 'title' attribute of your captcha iframe? The containing div should be at the bottom of the body HTML, and the hierarchy should look like this:
```
<div>
    <div></div>
    <div>
        <iframe title="recaptcha challenge">...</iframe>
    </div>
</div
```
Also, let me know if your HTML layout isn't the same as the above example.

**Comment by Czekoladowy** [comment]
This?

http://i.imgur.com/SWyKJef.png

**Comment by naschorr** [comment]
The div at the bottom, with the `visibility: "hidden"` style. It should expand into this: http://i.imgur.com/DdQrZAq.png

**Comment by Czekoladowy** [comment]
http://i.imgur.com/nbGsLty.png

**Comment by naschorr** [comment]
Actually, it might be easier just to dump the HTML by typing `document.documentElement.outerHTML;` into the console.

**Comment by Czekoladowy** [comment]
var script = document.createElement('script');
script.src = "https://rawgit.com/dd7531/autopxls/master/autopxls.js";
script.onload = function () {
var images = [
{
title: "isis",
x: 326,
y: 881,
image: "http://i.imgur.com/SqEZOat.png"
}
]
AutoPXLS(images);
};
document.head.appendChild(script);

**Comment by Czekoladowy** [comment]
This script working
